#!/usr/bin/env bash
#
# Build custom KDE packages for the arches-local repo.
#
# Called by build-aur-repo.sh during ISO build. Receives:
#   REPO_DIR               — directory to copy built .pkg.tar.* files into
#   BUILD_DIR              — scratch directory for builds
#   PLATFORM               — target platform (e.g. x86-64)
#   FORCE                  — "true" to rebuild regardless of cache
#   ARCHES_BUILD_CACHE_LIB — path to the build cache helper library
#
# This script builds:
#   1. Custom cmake plasmoids (task manager)
#   2. Patched distro packages (kwin with gesture patches)
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

: "${REPO_DIR:?REPO_DIR must be set}"
: "${BUILD_DIR:?BUILD_DIR must be set}"
: "${FORCE:=false}"

# Source build cache helpers
if [[ -n "${ARCHES_BUILD_CACHE_LIB:-}" && -f "$ARCHES_BUILD_CACHE_LIB" ]]; then
    source "$ARCHES_BUILD_CACHE_LIB"
else
    # Fallback: try relative path from project root
    source "$PROJECT_ROOT/scripts/lib/build-cache.sh"
fi

# ── Custom cmake plasmoids ────────────────────────────
# Each entry: local_dir:package_name
CUSTOM_CMAKE_PACKAGES=(
    "$PROJECT_ROOT/../kde-task-manager:arches-taskmanager-patched"
)

# Per-package extra makedepends (space-separated).
declare -A CUSTOM_EXTRA_MAKEDEPS=(
    ["arches-taskmanager-patched"]="git kconfig ki18n kio knotifications kservice kwindowsystem plasma-activities plasma-activities-stats libplasma libksysguard kitemmodels plasma-workspace"
)

# Per-package extra runtime depends (space-separated).
declare -A CUSTOM_EXTRA_DEPS=(
    ["arches-taskmanager-patched"]=""
)

# ── Patched distro packages ──────────────────────────
# Each entry: local_dir|package_name|upstream_repo|upstream_tag
# (pipe-delimited because URLs contain colons)
PATCHED_DISTRO_PACKAGES=(
    "$PROJECT_ROOT/../kwin-gestures|arches-kwin-patched|https://invent.kde.org/plasma/kwin|v6.6.4"
)

# --------------------------------------------------------------------------
# Build helpers
# --------------------------------------------------------------------------

build_cmake_package() {
    local src_dir="$1"
    local pkg_name="$2"

    if [[ ! -d "$src_dir" ]]; then
        # Check cache before failing — the source directory may only be
        # available on the developer's machine, not in CI or other builders.
        if [[ "$FORCE" == false ]] && compgen -G "$REPO_DIR/${pkg_name}-*.pkg.tar.*" &>/dev/null; then
            echo "── Custom: $pkg_name (source missing, using cached package) ──"
            return 0
        fi
        echo "ERROR: Source directory not found: $src_dir" >&2
        return 1
    fi

    local src_dir_abs
    src_dir_abs="$(cd "$src_dir" && pwd)"

    # ── Cache check ──
    local hash
    hash=$(compute_cache_hash "$src_dir_abs")
    if [[ "$FORCE" == false ]] && pkg_cache_hit "$REPO_DIR" "$pkg_name" "$hash"; then
        echo "── Custom: $pkg_name (cached, skipping) ──"
        return 0
    fi

    # Extract version from CMakeLists.txt
    local version
    version=$(grep -oP '(?:PROJECT_VERSION\s+"|project\([^)]*VERSION\s+)\K[0-9]+\.[0-9]+\.[0-9]+' \
              "$src_dir_abs/CMakeLists.txt" | head -1)
    version="${version:-0.0.1}"

    remove_stale_packages "$REPO_DIR" "$pkg_name"

    local pkg_build_dir="$BUILD_DIR/$pkg_name"
    rm -rf "$pkg_build_dir"
    mkdir -p "$pkg_build_dir"

    # Gather per-package deps
    local extra_makedeps="${CUSTOM_EXTRA_MAKEDEPS[$pkg_name]:-}"
    local extra_deps="${CUSTOM_EXTRA_DEPS[$pkg_name]:-}"
    local makedeps_str="'cmake' 'extra-cmake-modules' 'gcc' 'qt6-base' 'qt6-declarative'"
    local deps_str="'plasma-workspace'"
    for d in $extra_makedeps; do makedeps_str+=" '$d'"; done
    for d in $extra_deps; do deps_str+=" '$d'"; done

    local is_taskmanager=false
    [[ "$pkg_name" == "arches-taskmanager-patched" ]] && is_taskmanager=true

    if $is_taskmanager; then
        cat > "$pkg_build_dir/PKGBUILD" <<EOF
# Auto-generated by modules/kde/build.sh
pkgname=$pkg_name
pkgver=$version
pkgrel=1
pkgdesc="Patched KDE Task Manager — full-height launchers on multi-row panels"
arch=('x86_64' 'aarch64')
license=('GPL-3.0-or-later')
depends=($deps_str)
makedepends=($makedeps_str 'git')

build() {
    local upstream_clone="/tmp/plasma-desktop-upstream-src"
    local upstream_tag="v\$pkgver"
    if [[ ! -d "\$upstream_clone" ]]; then
        git clone --depth 1 --branch "\$upstream_tag" --filter=blob:none --sparse \\
            "https://invent.kde.org/plasma/plasma-desktop" "\$upstream_clone"
        git -C "\$upstream_clone" sparse-checkout set applets/taskmanager kcms/recentFiles
    fi

    local qs="\$upstream_clone/applets/taskmanager"
    mkdir -p src/qml/code

    for f in backend.cpp backend.h smartlauncherbackend.cpp smartlauncherbackend.h \\
              smartlauncheritem.cpp smartlauncheritem.h main.xml metadata.json; do
        cp "\$qs/\$f" src/
    done
    cp "\$upstream_clone/kcms/recentFiles/kactivitymanagerd_plugins_settings.kcfgc" src/
    cp "\$upstream_clone/kcms/recentFiles/kactivitymanagerd_plugins_settings.kcfg" src/

    cp "\$qs"/qml/*.qml src/qml/
    cp "\$qs"/qml/code/*.js src/qml/code/
    cp "$src_dir_abs/CMakeLists.txt" src/CMakeLists.txt
    patch -p1 -d src < "$src_dir_abs/fullheight-launchers.patch"

    cmake -S src -B build \\
        -DCMAKE_BUILD_TYPE=Release \\
        -DCMAKE_INSTALL_PREFIX=/usr \\
        -DBUILD_TESTING=OFF
    cmake --build build --parallel
}

package() {
    DESTDIR="\$pkgdir" cmake --install build
}
EOF
    else
        cat > "$pkg_build_dir/PKGBUILD" <<EOF
# Auto-generated by modules/kde/build.sh
pkgname=$pkg_name
pkgver=$version
pkgrel=1
pkgdesc="Custom Arches plasmoid: $pkg_name"
arch=('x86_64' 'aarch64')
license=('GPL-3.0-or-later')
depends=($deps_str)
makedepends=($makedeps_str)

build() {
    cmake -S "$src_dir_abs" -B build \\
        -DCMAKE_BUILD_TYPE=Release \\
        -DCMAKE_INSTALL_PREFIX=/usr \\
        -DBUILD_TESTING=OFF
    cmake --build build --parallel
}

package() {
    DESTDIR="\$pkgdir" cmake --install build
}
EOF
    fi

    echo "── Building custom: $pkg_name ($version) ──"
    cd "$pkg_build_dir"
    makepkg -s --noconfirm --skipchecksums
    cp ./*.pkg.tar.* "$REPO_DIR/"
    save_cache_hash "$REPO_DIR" "$pkg_name" "$hash"
    echo "  Built: $pkg_name"
}

build_patched_distro_package() {
    local patch_dir="$1"
    local pkg_name="$2"
    local upstream_repo="$3"
    local upstream_tag="$4"

    if [[ ! -d "$patch_dir" ]]; then
        # Check cache before failing — the patch directory may only be
        # needed on the developer's machine, not in CI or other builders.
        if [[ "$FORCE" == false ]] && compgen -G "$REPO_DIR/${pkg_name}-*.pkg.tar.*" &>/dev/null; then
            echo "── Patched: $pkg_name (source missing, using cached package) ──"
            return 0
        fi
        echo "ERROR: Patch directory not found: $patch_dir" >&2
        return 1
    fi

    local patch_dir_abs
    patch_dir_abs="$(cd "$patch_dir" && pwd)"

    # ── Cache check ──
    # Hash the patch files + upstream tag (tag change = rebuild)
    local hash
    hash=$(compute_cache_hash "$patch_dir_abs" "str:$upstream_tag")
    if [[ "$FORCE" == false ]] && pkg_cache_hit "$REPO_DIR" "$pkg_name" "$hash"; then
        echo "── Patched: $pkg_name (cached, skipping) ──"
        return 0
    fi

    local version="${upstream_tag#v}"

    remove_stale_packages "$REPO_DIR" "$pkg_name"

    local pkg_build_dir="$BUILD_DIR/$pkg_name"
    rm -rf "$pkg_build_dir"
    mkdir -p "$pkg_build_dir"

    # Collect all .patch files
    local patch_files=()
    local patch_sources=""
    local patch_apply=""
    for pf in "$patch_dir_abs"/*.patch; do
        [[ -f "$pf" ]] || continue
        local basename
        basename="$(basename "$pf")"
        cp "$pf" "$pkg_build_dir/$basename"
        patch_files+=("$basename")
        patch_sources+="        '$basename'"$'\n'
        patch_apply+="    patch -p1 -d \$_srcname < \"\$srcdir/$basename\""$'\n'
    done

    if [[ ${#patch_files[@]} -eq 0 ]]; then
        echo "WARNING: No .patch files found in $patch_dir_abs — skipping $pkg_name"
        return 0
    fi

    cat > "$pkg_build_dir/PKGBUILD" <<PKGEOF
# Auto-generated by modules/kde/build.sh
_srcname=kwin-$version
pkgname=$pkg_name
pkgver=$version
pkgrel=1
pkgdesc="KWin compositor — patched: 3-finger swipe for Overview"
arch=('x86_64' 'aarch64')
license=('LGPL-2.0-or-later')
provides=('kwin')
conflicts=('kwin')
replaces=('kwin')
depends=(
    'aurorae' 'breeze' 'gcc-libs' 'glibc' 'iio-sensor-proxy'
    'plasma-activities' 'kauth' 'kcmutils' 'kcolorscheme' 'kconfig'
    'kcoreaddons' 'kcrash' 'kdbusaddons' 'kdeclarative' 'kdecoration'
    'kglobalaccel' 'kglobalacceld' 'kguiaddons' 'ki18n' 'kidletime'
    'kirigami' 'kitemmodels' 'knewstuff' 'knighttime' 'knotifications'
    'kpackage' 'kquickcharts' 'kscreenlocker' 'kservice' 'ksvg'
    'kwayland' 'kwidgetsaddons' 'kwindowsystem' 'kxmlgui'
    'lcms2' 'libcanberra' 'libdisplay-info' 'libdrm' 'libei' 'libepoxy'
    'libevdev' 'libinput' 'libpipewire'
    'libqaccessibilityclient-qt6' 'libxcb' 'libxcvt' 'libxkbcommon'
    'mesa' 'milou' 'pipewire-session-manager' 'libplasma' 'qt6-5compat'
    'qt6-base' 'qt6-declarative' 'qt6-svg' 'qt6-tools' 'systemd-libs'
    'wayland' 'xcb-util-keysyms' 'xcb-util-wm'
)
makedepends=(
    'extra-cmake-modules' 'kdoctools' 'krunner'
    'plasma-wayland-protocols' 'python' 'wayland-protocols'
    'xorg-xwayland' 'git'
)
source=(
    "\$_srcname::git+${upstream_repo}#tag=${upstream_tag}"
$patch_sources)
sha256sums=('SKIP'
$(for _ in "${patch_files[@]}"; do echo "            'SKIP'"; done))

prepare() {
$patch_apply
}

build() {
    cmake -B build -S \$_srcname \\
        -DCMAKE_INSTALL_PREFIX=/usr \\
        -DCMAKE_INSTALL_LIBEXECDIR=lib \\
        -DCMAKE_BUILD_TYPE=Release \\
        -DBUILD_TESTING=OFF
    # Limit parallelism — kwin is a huge C++ project where heavy TUs
    # (e.g. tabbox, effects, compositing) can each consume 2-4 GB.
    # Cap at available_GB/4, with a floor of 2 and ceiling of 8.
    local mem_gb=\$(awk '/MemAvailable/{printf "%d", \$2/1048576}' /proc/meminfo)
    local jobs=\$(( mem_gb / 4 ))
    [[ \$jobs -lt 2 ]] && jobs=2
    [[ \$jobs -gt 8 ]] && jobs=8
    echo "  kwin: building with \$jobs parallel jobs (\${mem_gb}G available)"
    cmake --build build --parallel \$jobs
}

package() {
    DESTDIR="\$pkgdir" cmake --install build
    setcap CAP_SYS_NICE=+ep "\$pkgdir/usr/bin/kwin_wayland"
}
PKGEOF

    echo "── Building patched distro package: $pkg_name ($version) ──"
    cd "$pkg_build_dir"
    makepkg -s --noconfirm --skipchecksums --skippgpcheck
    cp ./*.pkg.tar.* "$REPO_DIR/"
    save_cache_hash "$REPO_DIR" "$pkg_name" "$hash"
    echo "  Built: $pkg_name"
}

# --------------------------------------------------------------------------
# Main
# --------------------------------------------------------------------------

echo "=== KDE module: building custom packages ==="

for entry in "${CUSTOM_CMAKE_PACKAGES[@]}"; do
    IFS=':' read -r src_dir pkg_name <<< "$entry"
    build_cmake_package "$src_dir" "$pkg_name"
done

for entry in "${PATCHED_DISTRO_PACKAGES[@]}"; do
    IFS='|' read -r patch_dir pkg_name upstream_repo upstream_tag <<< "$entry"
    build_patched_distro_package "$patch_dir" "$pkg_name" "$upstream_repo" "$upstream_tag"
done

echo "=== KDE module: custom packages built ==="
